export enum ERROR_CODE_MESSAGES {
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_NOT_AUTHORIZED = "USER_NOT_AUTHORIZED",
    USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
}

