export const FRONTEND_URL = Bun.env.FRONTEND_URL;
export const BACKEND_URL = Bun.env.BACKEND_URL;
export const PORT = Number(Bun.env.PORT) || 3000;
export const NODE_ENV = Bun.env.NODE_ENV || 'production';
export const REDIS_PASSWORD = Bun.env.REDIS_PASSWORD;
export const REDIS_HOST = Bun.env.REDIS_HOST || 'localhost';
export const REDIS_PORT = Number(Bun.env.REDIS_PORT) || 6379;
export const REDIS_USERNAME = Bun.env.REDIS_USERNAME || 'default';
export const DB_URL = Bun.env.DB_URL;
